### ISSUE TITLE
@transition not defined in scss file & empty initscss folder

### ISSUE THREAD

**Issue by brittanynavin** [nandomoreirame/zetsu#2]
**Just forked your repo and I noticed an issue with the _layout.scss file:**
When running `Jekyll serve` i get error `Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss': Undefined mixin 'transition'. on line 28` This happens additionally in all other lines where `transition` is defined. I took out all instanced of this in the file to get it to compile.

**Another issue is was found in the main.scss file:**
Additionally, I noticed there was nothing in the `initscss` folder, so the error of `Conversion error: Jekyll::Converters::Scss encountered an error while converting 'css/main.scss':
                    File to import not found or unreadable: initscss/scss/init. Load path: /Users/brittanyvacchiano/zetsu/_sass on line 10` occurs. I fixed this by removing the empty initscss folder and removing that import from the `main.scss` file on line 13. What did you mean to put in this folder?

Great job with the layout - can't wait to get my site looking exactly like yours & writing some posts.

**Comment by nandomoreirame** [comment]
Hi @bvacchiano, I'm sorry.

I made new updates and fix these errors

Please update your fork with the master and read the file **README.md** for the new version details

Thanks.

**Comment by nandomoreirame** [comment]
Hi @bvacchiano , I'll close this question ok?

bye.
